<a href="<?php echo $this->url('quotation', array('action'=>'index'));?>">Cancel</a><br><br>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('quotation', array('action' => $this->action, 'id' => $this->id)));
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<?php foreach ($form as $element) : ?>
 
    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
            if ('submit' != $element->getAttribute('type')) { ?>
                <label class="control-label"><?php echo $element->getLabel() ?></label>
                <?php
                $element->setAttribute('class', 'form-control');
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            echo $this->formElement($element);
            if ($this->formElementErrors($element)) : ?>
                <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<p class="help-block">')
                    ->setMessageSeparatorString('</p><p class="help-block">')
                    ->setMessageCloseString('</p>')
                    ->render($element);
                ?>
            <?php endif; ?>
    </div>
 
<?php
endforeach;
echo $this->form()->closeTag();
?>