<?php
$this->headLink()->appendStylesheet('/css/fmsport.css');
$title = 'Active projects';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('project', array('action'=>'add'));?>">New project</a>&nbsp;&nbsp;|&nbsp;&nbsp;
   <a href="<?php echo $this->url('project', array('action'=>'archived'));?>">Archived projects</a></p>
<?php
    echo $this->partial('/partials/index', array(
    		'debut' => $debut,
    		'tri' => $tri,
    		'desc' => $desc,
    		'paginator' => $paginator,
    		'update' => 'update',
    ));
?>
