<?php

$title = 'Delete a quotation';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
<a href="<?php echo $this->url('quotation', array('action'=>'index'));?>">Cancel</a><br><br>
<?php
$url = $this->url('quotation', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>

