<?php
$this->headLink()->appendStylesheet('/css/fmsport.css');
$title = 'Active quotations';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('quotation', array('action'=>'add'));?>">New quotation</a>&nbsp;&nbsp;|&nbsp;&nbsp;
   <a href="<?php echo $this->url('quotation', array('action'=>'archived'));?>">Archived quotations</a></p>
<?php
    echo $this->partial('/partials/qindex', array(
    		'debut' => $debut,
    		'tri' => $tri,
    		'desc' => $desc,
    		'paginator' => $paginator,
    		'update' => 'update',
    ));
?>
